
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["cn_n"].IsString) { throw new SerializationException(); }  CnN = _buf["cn_n"]; }
        { if(!_buf["en"].IsString) { throw new SerializationException(); }  En = _buf["en"]; }
    }

    public static Language DeserializeLanguage(JSONNode _buf)
    {
        return new Language(_buf);
    }

    /// <summary>
    /// 多语言key
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 简中
    /// </summary>
    public readonly string CnN;
    /// <summary>
    /// 英语
    /// </summary>
    public readonly string En;
   
    public const int __ID__ = -1548945544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "cnN:" + CnN + ","
        + "en:" + En + ","
        + "}";
    }
}

}
